# set ip address of watertank
tank_ipaddress=10.10.10.2
# set ip port of watertank
tank_port=30050
# set the level controller tries to achieve 
setpoint=70
# set the delta allowed/forced above and below the setpoint
delta=5
# set the percentage change per update period
increment=1
# set the update period in microseconds
update_period=1000000
