apiVersion: apps/v1
kind: Deployment
metadata:
  name: levelcontroller
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
        - image: docker.io/rmoorewrs/levelcontroller:latest
          name: levelcontroller
          ports:
            - containerPort: 5051
              protocol: TCP
      restartPolicy: Always
