apiVersion: apps/v1
kind: Deployment
metadata:
  name: levelcontroller
spec:
  selector:
    matchLabels:
      app: levelcontroller
  replicas: 1
  template:
    metadata:
      labels:
        app: levelcontroller
    spec:
      containers:
        - image: docker.io/rmoorewrs/levelcontroller:latest
          name: levelcontroller
          ports:
            - containerPort: 5051
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: levelcontroller
spec:
  type: NodePort
  selector:
    app: levelcontroller
  ports:
    - name: "5051"
      port: 5051
      targetPort: 5051
      nodePort: 30051
