apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
spec:
  selector:
    matchLabels:
      app: nodered
  replicas: 1
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
        - image: docker.io/rmoorewrs/vwt_custom_nodered:latest
          name: nodered
          ports:
            - containerPort: 1880
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nodered
spec:
  type: NodePort
  selector:
    app: nodered
  ports:
    - name: "1880"
      port: 1880
      targetPort: 1880
      nodePort: 30880


