---
watertank:
    tank_ip_address: 'watertank'
    tank_ip_port: '5050'
    name: 'Tank'
levelcontroller:
    controller_ip_address: 'levelcontroller'
    controller_ip_port: '5051'
    level_setpoint: '70'
    level_delta: '5'
    name: 'Controller'
